### ISSUE TITLE
Documentation: data must be pandas df?

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#14]
It is unclear from the documentation what the "data" argument should be.  Does this need to be a pandas dataframe?

x, y, and z also say they are lists of strings, but they need to be more than that -- they need to be column names from the pandas data frame, correct?  This should be indicated.

**Comment by hknd23** [comment]
To answer your question, the data type needs to be a pandas.DataFrame. We have included this information to the API and examples in the documentation. The descriptions for x, y, and z in our model functions in our revised and reorganized documentation indicate (as per your suggestion) that they need to be a list with the elements being column names taken from the dataset.

**Comment by cmaimone** [comment]
It is really helpful where you added this information, but it isn't on all of the functions (but is on most).  Is there a reason why it's omitted from some functions, such as the results functions?

**Comment by hknd23** [comment]
We had previously excluded the information (and description) that you refer to since the functions that report the results are nested within the model function, which means that they are less likely to be used on their own. However, in response to your point, we have added the necessary information and a more detailed description to each function in IDCeMPy to ensure consistency with the rest of the package.
