### ISSUE TITLE
Paper: section header Package Architecture

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#6]
I found the Package Architecture header in the paper confusing/misleading - I expected to see something about the structure of the package, but until I got to the list of functions, it seems to be more about implementation of the algorithms, followed by example use cases.  Consider re-organizing/re-titling this material a bit.

**Comment by hknd23** [comment]
We apologize for the confusion caused by the weak organization of the “Package Architecture” section in the previous version of our paper. We have thus addressed your suggestion in our revised paper as follows. To start, we use the title “Functionality and Applications” rather than Package Architecture in the revised paper as this new title describes the section’s content more accurately. Next, following your advice, the revised section mentioned above directly begins with the list of the functions in our IDCEMPy package and a bullet-point summary of what users can obtain from implementing each function. We then briefly mention the example use cases in our paper that illustrate the key features of the package’s listed functions that fit various inflated discrete choice models. Finally, we cut the description of the statistical models offered by the IDECEMPy package (this was included in the paper’s previous version) since it is not only redundant but also to ensure that the section focuses on emphasizing the package’s functionality.
