### ISSUE TITLE
Paper: consistency in referring to documentation

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#7]
The paper refers readers both to the GitHub repository and readthedocs documentation -- is there a primary location you want people to go?  For example, the Application section I expected to see you direct people to the documentation, not GitHub.  Not a huge deal, but it would be helpful to be clear about the primary location people should be going to (I'd assume the documentation).

**Comment by hknd23** [comment]
We addressed this suggestion by emphasizing in our paper that readers should refer to our package’s readthedocs documentation (https://idcempy.readthedocs.io/en/latest/),  which serves (instead of the GitHub repository) as the primary location for the examples/tutorials and the code required to fit the presented statistical models. This is stated in our revised paper’s “Functionality and Applications” section and “Summary” section. We, however, also provide the link to the GitHub repository in which our Python package is publicly available.
