### ISSUE TITLE
Documentation: independent examples

### ISSUE THREAD

**Issue by cmaimone** [hknd23/idcempy#9]
It would be helpful if the examples of using the package in the documentation were each independent of each other -- if each section had a complete example, starting with package imports.  That way, if someone goes to a section to see how to run one of the models, they have the complete code.

Also check that all of the packages you import in the example code are actually used.  numpy is imported, but I'm not sure that's necessary for all of the examples.

**Comment by cmaimone** [comment]
The last example? https://idcempy.readthedocs.io/en/latest/zmiopc_tutorial.html#outcome-equation-predicted-probabilities - seems to have a formatting issue maybe?  Looks like a function definition/API listing, but I think it's just another example?

**Comment by hknd23** [comment]
We incorporated this suggestion by first updating our documentation and then creating an ‘Examples” section.  This allowed us to organize all our examples (using package imports), which are now independent of each other.  Users can now go to each of the different examples to see how to run each of the models included in our package. Numpy is indeed not needed to run our models, so we deleted all the references to the aforementioned package. 
Furthermore, we have removed the sections with formatting issues. As mentioned earlier, we re-organized the package’s documentation so that users can now read instructions on how to estimate and plot the predicted probabilities in the examples of the ZiOP, ZiOPC, MiOP, and MiOPC models in their respective sections.
